### ISSUE TITLE
Allow viewing CSS files

### ISSUE THREAD

**Issue by Gitoffthelawn** [tim-we/web-ext-inspector#4]
Thank you for the helpful extension and web-app.

Could you allow viewing the contents of CSS files?

**Comment by tim-we** [comment]
Yes I agree this should be possible.

**Comment by tim-we** [comment]
Done :)

**Comment by Gitoffthelawn** [comment]
Great! Thanks!

Is it supposed to be live yet?

I tried it on:  
https://tim-we.github.io/web-ext-inspector/?extension=tabs-aside

but no CSS file contents listed.

**Comment by tim-we** [comment]
Yes it is supposed to be live, works for me. Maybe a caching issue? Can you try it in a private window? If it is a caching issue please create a GitHub issue.


https://user-images.githubusercontent.com/10491533/132945508-c00189cd-f7f6-4bb2-8852-6fbf0d0e150c.mp4

**Comment by Gitoffthelawn** [comment]
Actually, it's not a caching issue.  It's a dumbass issue.  I expected the file to be displayed without having to press the 'Open' button.  Sorry for my silliness.

As the screencast you uploaded shows, it would be nice if the extension inspector could perform word-wrap.  It will be especially useful for minified code.

BTW, which screen recorder did you use?  The output looks real good and is compressed nicely.

**Comment by tim-we** [comment]
I use OBS for screen recording. This video is actually re-encoded with ffmpeg because dumbass me recorded people talking in the background :D

Yes word-wrap would be nice but running the code through something like prettier would be even better I think and would help a lot with minified code.

**Comment by Gitoffthelawn** [comment]
LOL... Funny how 2 smart people can both be dumbasses within a few minutes of each other! LOL.

Yes, prettifying would be even better than word-wrap.  I mentioned word-wrap because it's so easy to implement, but prettifying would be great!
