### ISSUE TITLE
UX Improvement: Allow selecting a new extension to view

### ISSUE THREAD

**Issue by Gitoffthelawn** [tim-we/web-ext-inspector#5]
When viewing an extension, there is currently no way to view a different extension.  What do you think about adding that functionality to improve the UX?

**Comment by tim-we** [comment]
Not sure what you mean by this. Perhaps
- getting back to the selection screen? I agree this should be possible.
- inspecting multiple extensions side-by-side?
or something else?

**Comment by Gitoffthelawn** [comment]
> getting back to the selection screen? I agree this should be possible.

This. :)

**Comment by tim-we** [comment]
I made the title "Extension Inspector" (and the logo) clickable, leading back to the selection screen. This is a bit hidden but I didn't know where to place a "close" button. If you have any suggestions, please let me know :)

If you think it's fine the way it is now just close the issue.

**Comment by Gitoffthelawn** [comment]
I think what you did gets the job done.  Thanks.

Would it be possible to allow it to support the back/forward browser buttons so that you can see, for example, the previous extension you inspected?

**Comment by tim-we** [comment]
Yes that is possible and I would like to support that. I don't have much experience with those APIs though, so I'll have to look into that when I find the time. PRs welcome :)

**Comment by Gitoffthelawn** [comment]
Sounds good.  Would you like me to create a separate issue report, or just keep it here?  Whatever you prefer is fine.

**Comment by tim-we** [comment]
I would prefer a separate issue, thanks :)

**Comment by Gitoffthelawn** [comment]
You bet.  I'll do it now.
