### ISSUE TITLE
Allow support for the back/forward web browser buttons

### ISSUE THREAD

**Issue by Gitoffthelawn** [tim-we/web-ext-inspector#7]
Would it be possible to allow it to support the back/forward browser buttons so that you can see, for example, the previous extension you inspected?

This is in regards to the new functionality added in response to #5.

For anyone else reading this, please note that the primary developer has welcomed a PR to help with this (see https://github.com/tim-we/web-ext-inspector/issues/5#issuecomment-903192436).

**Comment by Gitoffthelawn** [comment]
Thanks for working on this. ❤️

**Comment by tim-we** [comment]
Should be working now. Note that the web extensions are not cached at the moment and are re-downloaded when doing the respective back or forward navigation.

**Comment by Gitoffthelawn** [comment]
Thank you!
